event_url: https://www.thaiticketmajor.com/performance/2026-byeonwooseok-asia-fanmeeting-tour-the-secret-library-in-bangkok.html

target_round:
  date: "2026-08-16"
  time: "17:00"

sale_start: "2026-07-05T10:00:00+07:00"
zone_priority: ["A1", "A2", "B1", "B2", "C1", "C2"]
ticket_count: 2
