event_url: https://www.thaiticketmajor.com/concert/pond-phuwin-space-soul-dyssey-concert.html

target_round:
  date: "2026-08-21"
  time: "18:00"

sale_start: "2026-06-28T10:00:00+07:00"
zone_priority: ["SB", "SC", "SD", "A2", "A3", "B2", "SE", "SF", "SJ", "SK", "SL", "SM", "SN"]
ticket_count: 2
