event_url: https://www.thaiticketmajor.com/concert/rookie-divos-concert.html

target_round:
  date: "2026-09-26"
  time: "18:00"

sale_start: "2026-06-27T10:00:00+07:00"
zone_priority: ["A2", "A3", "C2", "C3"]
ticket_count: 2
